### ISSUE TITLE
Unicode Support Tracking

### ISSUE THREAD

**Issue by Shinmera** [Shirakumo/alloy#5]
This is an issue to track the implementation of support libraries to correctly deal with Unicode.

- [x] uax-9 https://github.com/Shinmera/uax-9
- [ ] uax-11 https://www.unicode.org/reports/tr11/
- [x] uax-14 https://github.com/Shinmera/uax-14
- [x] uax-15 https://github.com/sabracrolleton/uax-15
- [ ] uax-29 https://www.unicode.org/reports/tr29/
- [ ] uax-50 https://www.unicode.org/reports/tr50/

Implementation of these annexes is necessary in order to proceed to writing a full text layout engine in Lisp.
